// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartPantry.DataAccess.Contexts;

#nullable disable

namespace SmartPantry.DataAccess.Migrations
{
    [DbContext(typeof(SmartPantryDbContext))]
    [Migration("20251030075616_ReplaceMealSuggestionWithRecipe")]
    partial class ReplaceMealSuggestionWithRecipe
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartPantry.Core.Entities.FoodProductEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Brands")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("date");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Quantity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserID");

                    b.ToTable("FoodProduct", (string)null);
                });

            modelBuilder.Entity("SmartPantry.Core.Entities.RecipeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IngredientsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserEntityId");

                    b.HasIndex("UserID");

                    b.ToTable("Recipe", (string)null);
                });

            modelBuilder.Entity("SmartPantry.Core.Entities.RecipeFoodProductEntity", b =>
                {
                    b.Property<Guid>("RecipeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FoodProductID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FoodProductEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("OrderIndex")
                        .HasColumnType("int");

                    b.HasKey("RecipeID", "FoodProductID");

                    b.HasIndex("FoodProductEntityId");

                    b.HasIndex("FoodProductID");

                    b.ToTable("RecipeFoodProduct", (string)null);
                });

            modelBuilder.Entity("SmartPantry.Core.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("SmartPantry.Core.Entities.FoodProductEntity", b =>
                {
                    b.HasOne("SmartPantry.Core.Entities.UserEntity", "User")
                        .WithMany("FoodProducts")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartPantry.Core.Entities.RecipeEntity", b =>
                {
                    b.HasOne("SmartPantry.Core.Entities.UserEntity", null)
                        .WithMany("Recipes")
                        .HasForeignKey("UserEntityId");

                    b.HasOne("SmartPantry.Core.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartPantry.Core.Entities.RecipeFoodProductEntity", b =>
                {
                    b.HasOne("SmartPantry.Core.Entities.FoodProductEntity", null)
                        .WithMany("RecipeFoodProducts")
                        .HasForeignKey("FoodProductEntityId");

                    b.HasOne("SmartPantry.Core.Entities.FoodProductEntity", "FoodProduct")
                        .WithMany()
                        .HasForeignKey("FoodProductID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SmartPantry.Core.Entities.RecipeEntity", "Recipe")
                        .WithMany("RecipeFoodProducts")
                        .HasForeignKey("RecipeID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("FoodProduct");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("SmartPantry.Core.Entities.FoodProductEntity", b =>
                {
                    b.Navigation("RecipeFoodProducts");
                });

            modelBuilder.Entity("SmartPantry.Core.Entities.RecipeEntity", b =>
                {
                    b.Navigation("RecipeFoodProducts");
                });

            modelBuilder.Entity("SmartPantry.Core.Entities.UserEntity", b =>
                {
                    b.Navigation("FoodProducts");

                    b.Navigation("Recipes");
                });
#pragma warning restore 612, 618
        }
    }
}
